### ISSUE TITLE
tomcat 8 redis session store

### ISSUE THREAD

**Issue by bkpraveen** [pivotalsoftware/session-managers#10]
I am trying to use this plugin in tomcat 8. Downloaded the latest code and did maven build add Valve and manager in context.xml, but when I bring up tomcat I am getting the following error

```
<Valve className="com.gopivotal.manager.PivotalSessionFlushValve" />
 <Manager className="org.apache.catalina.session.PersistentManager">
 <Store className="com.gopivotal.manager.redis.RedisStore"  host="localhost" port="6379"/>
</Manager>
```

25-Oct-2016 15:36:45.145 SEVERE [localhost-startStop-1] com.gopivotal.manager.LockTemplate.withReadLock Error while invoking read-locked operation
 java.lang.IllegalArgumentException: javax.management.InstanceAlreadyExistsException: Catalina:type=Valve,context=/,host=localhost,name=PivotalSessionFlushValve
        at com.gopivotal.manager.StandardJmxSupport.register(StandardJmxSupport.java:47)
        at com.gopivotal.manager.PivotalSessionFlushValve$8.invoke(PivotalSessionFlushValve.java:177)
        at com.gopivotal.manager.PivotalSessionFlushValve$8.invoke(PivotalSessionFlushValve.java:173)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        at com.gopivotal.manager.PivotalSessionFlushValve.startInternal(PivotalSessionFlushValve.java:173)
        at com.gopivotal.manager.AbstractLifecycle.start(AbstractLifecycle.java:122)
        at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:170)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5214)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.management.InstanceAlreadyExistsException: Catalina:type=Valve,context=/,host=localhost,name=PivotalSessionFlushValve
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.gopivotal.manager.StandardJmxSupport.register(StandardJmxSupport.java:45)
        ... 19 more

I tried changing the name of the Valve class to PivotalSessionFlushValve, still gave the same error instancealreadyexists.

Please let me know If I am missing anything.

**Comment by jkonicki** [comment]
The latest (1.3.x) works with Tomcat 8.5. 
1.2.0 works with Tomcat 8.

**Comment by bkpraveen** [comment]
How do I get the 1.3

**Comment by jkonicki** [comment]
You can use v1.3.1.RELEASE tag.

**Comment by bkpraveen** [comment]
thanks for responding back so quickly I tried 1.3.1 and still seeing the same error


Caused by: java.lang.IllegalArgumentException: javax.management.InstanceAlreadyExistsException: Catalina:type=Valve,context=/,host=localhost,name=SessionFlushValve
        at com.gopivotal.manager.StandardJmxSupport.register(StandardJmxSupport.java:47)
        at com.gopivotal.manager.SessionFlushValve$8.invoke(SessionFlushValve.java:177)
        at com.gopivotal.manager.SessionFlushValve$8.invoke(SessionFlushValve.java:173)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        ... 16 more
Caused by: javax.management.InstanceAlreadyExistsException: Catalina:type=Valve,context=/,host=localhost,name=SessionFlushValve
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.gopivotal.manager.StandardJmxSupport.register(StandardJmxSupport.java:45)
        ... 19 more

**Comment by bkpraveen** [comment]
correction I am using Apache Tomcat/8.0.36
I tried release 1.2 and still seeing the same error.

**Comment by bkpraveen** [comment]
Hi 
I figured I was using a tomcat binary as 1 base directory and app specific tomcat to share the binary.
somehow this confused the plugin and tried to register the mbean probably.
I was able to work around this by putting the sessionvalve in the base directory tomcat context xml.
Thanks for your help.

One last question does it remove the keys from redis when the users logout or when tomcat kills the session?

**Comment by ccheetham** [comment]
Not sure to what you refer by keys.  Could be "key" as in a session's session ID.  Or could be "key" as in a session property's name.

In either of these cases, `redis-store` does nothing to managed sessions upon user logout or tomcat death.

In the case of user logout, logout is an application-level concept.  Neither the PersistenceManager or `redis-store` have notions of login/logout.

In the case of Tomcat death, a main point of using a PersistenceManager such as `redis-store` is for sessions to survive restarts.  Neither PersistenceManager nor `redis-store` destroy sessions in this scenario.
