### ISSUE TITLE
SEVERE: Error while invoking read-locked operation

### ISSUE THREAD

**Issue by kailt** [pivotalsoftware/session-managers#20]
I get this error on saving a session:

```
SEVERE: Error while invoking read-locked operation
 java.lang.NullPointerException
	at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:167)
	at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:158)
	at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
	at com.gopivotal.manager.SessionFlushValve.invoke(SessionFlushValve.java:158)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.valves.CrawlerSessionManagerValve.invoke(CrawlerSessionManagerValve.java:180)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using **Tomcat 7** and I downloaded **session-managers v1.2.0**. I ran mvn package and copied the redis-store-1.2.0.RELEASE.jar from the target directory to Tomcat/lib.

In my webapp's context.xml, I've added the following lines:

```
  <Valve className="com.gopivotal.manager.SessionFlushValve" />
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store
      className="com.gopivotal.manager.redis.RedisStore"
      connectionPoolSize="-1"
      database="1"
      host="localhost"
      port="6379"
      timeout="5000"
    />
  </Manager>
```

**Comment by kailt** [comment]
I've traced the code and RedisStore.initInternal() is not being called on Tomcat initialization.

**Comment by ccheetham** [comment]
Can you details on specific versions you are using?  Even better, a test case?

In my setup I'm using Tomcat 7.0.72, Redis 3.2.8, Java 1.8.0_92 (OSX).  I built the session manager from source using tag v1.2.0.RELEASE.  In my setup, RedisStore.initInternal is called when Tomcat starts.

**Comment by ccheetham** [comment]
Closing, but please feel free to reopen with any updates.

**Comment by ccheetham** [comment]
Closing, but please feel free to reopen with any updates.

**Comment by ccheetham** [comment]
Closing, but please feel free to reopen with any updates.
