### ISSUE TITLE
v1.2.2 and v1.3.3 do not seem to work with java buildpack v3.18

### ISSUE THREAD

**Issue by sambryant4** [pivotalsoftware/session-managers#45]
It looks like the change to `slf4j` to set its scope as `provided` has stopped session managers working with the java buildpack. We have been able to successfully test using `v1.2.1` and `v1.3.2` and earlier without issue.

The error message we get when trying to stage apps is:
```
2017-07-13T09:36:59.39+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Initializing ProtocolHandler ["http-nio-8080"]
2017-07-13T09:36:59.40+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.Catalina               INFO    Initialization processed in 386 ms
2017-07-13T09:36:59.42+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardService           INFO    Starting service Catalina
2017-07-13T09:36:59.42+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardEngine            INFO    Starting Servlet Engine: Apache Tomcat/8.0.44
2017-07-13T09:36:59.44+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.HostConfig             INFO    Deploying web application directory /home/vcap/app/.java-buildpack/tomcat/webapps/ROOT
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.tomcat.util.digester.Digester           SEVERE  Begin event threw error
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at com.gopivotal.manager.AbstractLifecycle.<init>(AbstractLifecycle.java:50)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at com.gopivotal.manager.StandardLifecycleSupport.<init>(StandardLifecycleSupport.java:32)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at com.gopivotal.manager.SessionFlushValve.<init>(SessionFlushValve.java:53)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
2017-07-13T09:36:59.50+0100 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

**Comment by ccheetham** [comment]
Re-worked 1.2 and 1.3 to declare slf4j-jdk14 as a runtime dep.

Note the shaded jar is no longer produced so you'll need to add the slf4j deps as well as some Apache and Jedis libs.  Maven/Gradle shoudl pull them in automatically.

The updated versions are 1.2.4.RELEASE and 1.3.5.RELEASE.

**Comment by shanman190** [comment]
So I ran into this as well, and what it appears is that the removal of the shaded jar is what caused the issue. It appears that in the context of the Java buildpack for Cloud Foundry that this jar is loaded and initialized as the tomcat container initializes, but before the webapp that will run inside of the Tomcat container has been added to the ServletContext or classpath. So in prior versions, the shaded jar was providing the slf4j dependency that way, so that Tomcat could initialize and then get the application loaded in which case all of the logging would then be controlled by the application via whichever logging framework that it chose.

To resolve this, I believe what needs to be done is that the slf4j-jdk14 jar needs to be removed and the shaded jar plugin needs to be re-added.

**Comment by ccheetham** [comment]
I believe the difference is in the packaging.  In the shaded jar, the SLF4J jdk14 binding is included, whereas in the non-shaded jar, the binding must be provided independently.  The intent of introducing SL4F4J was to provide additional logging options for packages of the session manager distribution.  Including the binding in the shaded jar obviates that intent.

If the Java buildpack for Cloud Foundry cannot provide the binding in its packaging, I believe the recourse is to remove the SLF4J integration, reverting back the the original logging impl (which happens to be JDK14 logging).

**Comment by jzingler** [comment]
Is there a workaround for teams using Java Buildpack 3.18? What version of the buildpack uses 1.3.5.RELEASE?

**Comment by shanman190** [comment]
@jzingler, so it depends on the build pack that you've got or when it was built. If you're using the online Java build pack, then all versions would be effected. If you're using the offline build pack, it would depend on when your operator built that Java build pack and what would have been available. The only work around that I know of is to explicitly set the redis store version as part of the Java build pack custom configuration as you deploy your application. See https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md for more details on how to achieve this.

@ccheetham, I've been thinking about this for a while and have kind of landed in this position... My thoughts are that the redis store should simply use JUL for it's logging framework and then make a note for any users utilizing it that it's in their best interest to take advantage of their chosen application logging to configure their logs to pick up this applications content. With that being said, Slf4j is just the first issue that was hit in this process of getting initialized and I think that the Apache and Jedis stuff would have come to be a problem as well. If you're really adamant about not having the shaded jar then the group maintaining the Java build pack will need to make some modifications to acquire your jar and it's couple of dependencies. The biggest problem with this jar having any dependencies at all, is that it's going to be loaded so early in the process and because of that could cause classpath pollution by inserting the Slf4j jar into tomcat (think newer/older version than what the application uses). I believe that this library needs to maintain the absolute smallest set of dependencies that it can, so that it can be a low impact to the application. With that said I think that there may not be a way around including Jedis for some reason and I'm not sure what Apache libraries are being utilized, as I'm writing this, but I would think that you'd want to analyze those to ensure that any of those dependencies wouldn't have an impact.

Since we've mentioned the Java build pack group making changes several times in this issue I think that it's about time that they be included in the conversation to get their input.

/cc @cloudfoundry/java-buildpack

**Comment by jzingler** [comment]
@shanman190 - For my scenario, the buidpack is offline and it is not possible to use an online buildpack due to security policies. If I change the offline buildpack to pull in a different redis store version, I believe it would attempt to reach out to the internet and fail. 

>The only work around that I know of is to explicitly set the redis store version as part of the Java build pack custom configuration as you deploy your application. See https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md for more details on how to achieve this.

**Comment by shanman190** [comment]
@jzingler When the offline buildpack is generated it actually downloads all of the available versions and stores those internally to the offline buildpack, so you should be able to utilize an older version of the redis store library by that mechanism.

**Comment by ccheetham** [comment]
We've backed out SLF4J, and reverted back to the shaded jars.

Java build pack 4.5.1 has above changes.
