### ISSUE TITLE
Error while invoking read-locked operation

### ISSUE THREAD

**Issue by stuartjackson23** [pivotalsoftware/session-managers#48]
I've been developing on the following:
Windows 7
Java 1.7.0_80
Tomcat 8.0.26
Redis 3.2.4 (on Amazon ElastiCache)
redis-store-1.2.1.RELEASE.jar (downloaded from GitHub and stored in $TOMCAT/lib directory)

I added this to my context.xml file:
```
	<Valve className="com.gopivotal.manager.SessionFlushValve"/>
	
	<Manager className="org.apache.catalina.session.PersistentManager">
		<Store className="com.gopivotal.manager.redis.RedisStore"
			host="myredisserver.wzpuvj.ng.0001.apse1.cache.amazonaws.com"
			database="2"
			connectionPoolSize="100"
			timeout="10000"
		/>
	</Manager>
```

All is working fine in development. Today I installed on my test server, which is:
Ubuntu 12.04
Java 1.7.0_80
Tomcat 8.0.26
Redis 3.2.4 (on Amazon ElastiCache - same server as above)
redis-store-1.2.1.RELEASE.jar (downloaded from GitHub and stored in $TOMCAT/lib directory)

I added the same Valve and Manager elements to context.xml. Tomcat starts without error, however when I try and go to a page in the webapp I get this (repeated) in my catalina logs:
```
20-Sep-2017 13:18:06.964 SEVERE [ajp-nio-8009-exec-1] com.gopivotal.manager.LockTemplate.withReadLock Error while invoking read-locked operation
 java.lang.NullPointerException
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:167)
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:158)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        at com.gopivotal.manager.SessionFlushValve.invoke(SessionFlushValve.java:158)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

I've also tried using versions 1.2.0, 1.3.0, 1.3.1 and 1.3.2 of the redis-store jar but all give the same error.

**Comment by stuartjackson23** [comment]
Looks the same as this thread, which never went anywhere:
https://github.com/pivotalsoftware/session-managers/issues/20

Thanks for your help!

**Comment by ccheetham** [comment]
Looks like the request is coming over AJP on an NIO connector.  If you issue the request over the HTTP connector do you still have the error?

Additionally, If you enable FINE for `com.gopivotal`, you should see something ala:
```
Setting 'com.gopivotal.manager.redis.RedisStore$23@40ee9b48' as the store for 'com.gopivotal.manager.SessionFlushValve@23db34d2'
```
in the `catalina.[DATE].log`.

**Comment by stuartjackson23** [comment]
If I issue the request over the HTTP connector the error looks like this:

```
21-Sep-2017 07:54:32.080 SEVERE [http-nio-8090-exec-4] com.gopivotal.manager.LockTemplate.withReadLock Error while invoking read-locked operation
 java.lang.NullPointerException
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:167)
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:158)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        at com.gopivotal.manager.SessionFlushValve.invoke(SessionFlushValve.java:158)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

I added this to my $TOMCAT/conf/logging.properties (not sure if this is what you meant):
`com.gopivotal.level = FINE`

But I don't see the message in the catalina.[DATE].log. Here is this file:

```
21-Sep-2017 07:34:37.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.26
21-Sep-2017 07:34:37.215 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 18 2015 11:38:37 UTC
21-Sep-2017 07:34:37.216 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.26.0
21-Sep-2017 07:34:37.216 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
21-Sep-2017 07:34:37.217 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.2.0-25-virtual
21-Sep-2017 07:34:37.217 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
21-Sep-2017 07:34:37.218 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/jdk1.7.0_80/jre
21-Sep-2017 07:34:37.218 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_80-b15
21-Sep-2017 07:34:37.218 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
21-Sep-2017 07:34:37.219 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/apache-tomcat-8.0.26
21-Sep-2017 07:34:37.220 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/apache-tomcat-8.0.26
21-Sep-2017 07:34:37.221 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/apache-tomcat-8.0.26/conf/logging.properties
21-Sep-2017 07:34:37.221 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
21-Sep-2017 07:34:37.222 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms2048m
21-Sep-2017 07:34:37.222 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
21-Sep-2017 07:34:37.223 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PermSize=256m
21-Sep-2017 07:34:37.223 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=256m
21-Sep-2017 07:34:37.223 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:-UseSplitVerifier
21-Sep-2017 07:34:37.224 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dhttps.protocols=TLSv1.2
21-Sep-2017 07:34:37.224 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.net.preferIPv4Stack=true
21-Sep-2017 07:34:37.225 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:-OmitStackTraceInFastThrow
21-Sep-2017 07:34:37.225 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.commons.collections.enableUnsafeSerialization=true
21-Sep-2017 07:34:37.225 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=4711,server=y,suspend=n
21-Sep-2017 07:34:37.226 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/local/apache-tomcat-8.0.26/endorsed
21-Sep-2017 07:34:37.226 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/apache-tomcat-8.0.26
21-Sep-2017 07:34:37.227 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/apache-tomcat-8.0.26
21-Sep-2017 07:34:37.227 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/apache-tomcat-8.0.26/temp
21-Sep-2017 07:34:37.228 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21-Sep-2017 07:34:37.784 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8090"]
21-Sep-2017 07:34:37.887 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Sep-2017 07:34:37.912 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
21-Sep-2017 07:34:37.919 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Sep-2017 07:34:37.939 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2620 ms
21-Sep-2017 07:34:38.078 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
21-Sep-2017 07:34:38.082 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.26
21-Sep-2017 07:34:38.133 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /usr/local/apache-tomcat-8.0.26/conf/Catalina/localhost/ROOT.xml
21-Sep-2017 07:34:38.398 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore.<init> Pivotal redis-store, 1.2.1.RELEASE
21-Sep-2017 07:34:38.406 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore.<init> Sessions will be persisted to Redis using a com.gopivotal.manager.redis.RedisStore
21-Sep-2017 07:34:38.413 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore$7.invoke setting host=myredisserver.wzpuvj.ng.0001.apse1.cache.amazonaws.com
21-Sep-2017 07:34:38.414 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore$5.invoke setting database=2
21-Sep-2017 07:34:38.421 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore$3.invoke setting connectionPoolSize=100
21-Sep-2017 07:34:38.422 INFO [localhost-startStop-1] com.gopivotal.manager.redis.RedisStore$16.invoke setting timeout=10000
21-Sep-2017 07:34:57.577 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
21-Sep-2017 07:36:04.318 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor /usr/local/apache-tomcat-8.0.26/conf/Catalina/localhost/ROOT.xml has finished in 86,170 ms
21-Sep-2017 07:36:04.350 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8090"]
21-Sep-2017 07:36:04.398 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
21-Sep-2017 07:36:04.409 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 86468 ms
```

Thanks.

**Comment by stuartjackson23** [comment]
In case it helps, here is my context.xml file (stripped of comments):

```
<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>

    <Valve className="com.gopivotal.manager.SessionFlushValve"/>

    <Manager className="org.apache.catalina.session.PersistentManager">
        <Store className="com.gopivotal.manager.redis.RedisStore"
            host="sedredisdev.wzpuvj.ng.0001.apse1.cache.amazonaws.com"
            database="2"
            connectionPoolSize="100"
            timeout="10000"
        />
    </Manager>
</Context>
```

And here are the two connectors defined in my server.xml file:
```
<Connector port="8090" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

 <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
```

**Comment by stuartjackson23** [comment]
I figured out the problem. On my test server I had this line in my $TOMCAT/conf/Catalina/localhost/ROOT.xml file:

`<Manager pathname="" />`

This disables session persistence across Tomcat restarts. I guess it makes sense that this will interfere with saving sessions in Redis. Hope this helps someone else and that's a lot for your help Chris.

**Comment by ccheetham** [comment]
That probably explains the absence of the missing log message about configuring valve-store.

I also noted a couple of missing key log messages:
```
... com.gopivotal.manager.redis.RedisStore.connect Connecting to Redis Server at redis://...
... com.gopivotal.manager.redis.RedisStore$26.invoke Connection to Redis Server successful
```

Thanks for posting your problem resolution!
