### ISSUE TITLE
SEVERE: Error while invoking read-locked operation

### ISSUE THREAD

**Issue by ajquiambao** [pivotalsoftware/session-managers#51]
Hi, I would like to ask what could be wrong on our setup. When I use the redis + tomcat +nginx. I don't get any error regarding Locktemplate but when we try to change the nginx and replace it with AWS Applcation Load balancer the Locktemplate shows in our logs.

Example Stacktrace:
`Caused by: java.lang.ClassCastException: java.lang.StackTraceElement cannot be cast to java.lang.String
	at java.io.ObjectInputStream.readTypeString(ObjectInputStream.java:1612)
	at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:719)
	at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:882)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1815)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1611)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1077)
	at com.gopivotal.manager.SessionSerializationUtils.deserialize(SessionSerializationUtils.java:81)
	at com.gopivotal.manager.redis.RedisStore$22.invoke(RedisStore.java:442)
	at com.gopivotal.manager.redis.RedisStore$22.invoke(RedisStore.java:436)
	at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
	... 24 more`

Tomcat Version: 8.5.27
redis-store-1.3.2.RELEASE.jar
redis-3.2.10-2.el7.x86_64

Here's my context.xml.

`<Valve className="com.gopivotal.manager.SessionFlushValve" />
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="com.gopivotal.manager.redis.RedisStore"
                         host="10.10.5.226"
                          port="6379"/>
  </Manager>`

I've already saw  some old issues regarding Locktemplate but none of them worked for me
(#48 )
(#20)

Any thoughts will be much appreciated.

**Comment by ajquiambao** [comment]
My bad,  found out by one of our developer that some objects in the checkout session weren't serialized that's why we are getting an error regarding read-locked. Closing this issue now.
